apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: label-node-role
  namespace: nfsprovisioner-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: label-node-role-binding
  namespace: nfsprovisioner-operator
subjects:
- kind: ServiceAccount
  name: label-node-service-account
roleRef:
  kind: Role
  name: label-node-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-node-service-account
  namespace: nfsprovisioner-operator