kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  namespace: mssql
  labels:
     app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  