apiVersion: v1
kind: Service
metadata:
  name: sqlserver-external
  namespace: mssql
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 31433
      targetPort: 1433
  type: LoadBalancer