kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
    - ../../operator/overlays/stable
    - ../../instance/knative-eventing/overlays/knative-kafka
    - ../../instance/knative-serving/overlays/default