apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  broker:
    defaultConfig:
      numPartitions: 10
      replicationFactor: 3
      bootstrapServers: 'my-cluster-kafka-bootstrap.amq-streams-kafka:9092'
    enabled: false
  channel:
    enabled: false
    bootstrapServers: 'my-cluster-kafka-bootstrap.amq-streams-kafka:9092'
  logging:
    level: INFO
  sink:
    enabled: false
  source:
    enabled: true
  logging:
    level: DEBUG