apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfs-provisioner-operator
  namespace: nfsprovisioner-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: nfs-provisioner-operator
  source: community-operators 
  sourceNamespace: openshift-marketplace 